name: ci

on:
  push:
    branches: 
      - master
jobs:
  ci:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm ci
      - name: Run lint
        run: npm run lint
      - name: Build
        run: npm run build